version: '{build}-{branch}'
image:
  - Visual Studio 2019

init:
  - net start MSSQL$SQL2019

services:
  - mysql

build_script:
  - pwsh: dotnet build -c Release /p:ContinuousIntegrationBuild=true

test_script:
  - pwsh: dotnet test ./test/MicroOrm.Dapper.Repositories.Tests -c Release --no-build

after_test:
  - pwsh: ./pack.ps1

artifacts:
  - path: '**\artifacts\nuget\*nupkg'
    name: NuGet
  - path: '**\artifacts\github\*nupkg'
    name: GitHub

deploy:

  - provider: NuGet
    api_key:
      secure: c7cEyPKwa2sV+LsQZO1QTgAgoSukaNuX5qkGMbxvwYOv6oqS2vU3cZgh5X56PLVf
    artifact: NuGet
    on:
      appveyor_repo_tag: true

  - provider: NuGet
    server: https://nuget.pkg.github.com/prom-client-net/index.json
    api_key:
      secure: U02HA+rgKPHNAQJ3u/r2Sr25u70JMpX/Gym5Z5VsWyrbe1b8c9lDJI8H8J/MdJZv
    artifact: GitHub
    on:
      branch: master
      appveyor_repo_tag: false
