version: '{build}-{branch}'
image: Visual Studio 2019

services:
- mssql2017
- mysql

build_script:
- pwsh: dotnet build -c Release

test_script:
- pwsh: dotnet test ./test/MicroOrm.Dapper.Repositories.Tests -c Release --no-build

after_test:
- pwsh: ./pack.ps1

artifacts:
- path: '**\artifacts\nuget\*.nupkg'
  name: NuGet
- path: '**\artifacts\myget\*.nupkg'
  name: MyGet

deploy:

- provider: NuGet
  api_key:
    secure: An+Cm24p8nt1T8n2ocBaFyrjIOzGI//Hs4gBMF7OcCLOHkZTmB60X6EP/+pWGIrN
  artifact: NuGet
  on:
    appveyor_repo_tag: true

- provider: NuGet
  server: https://www.myget.org/F/phnx47-beta/api/v2/package
  api_key:
    secure: sra89qUYhiuc146gUszl0lg1u3tWG1Zc65B7lgVuZlIfxyq/3w4q3mkXeBiLpNA5
  symbol_server: https://www.myget.org/F/phnx47-beta/symbols/api/v2/package
  artifact: MyGet
  on:
    branch: master
    appveyor_repo_tag: false
