version: '3.9'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Password12!

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12!
    ports:
      - "1433:1433"
    restart: always

  oracle:
    image: quay.io/maksymbilenko/oracle-12c:latest
    ports:
      - "1521:1521"
      - "8080:8080"
    restart: always
